"""Role constants and helpers for access control."""

ROLE_PATIENT = 'patient'
ROLE_ADMIN = 'admin'
ROLE_HEAD = 'head'
ROLE_NURSE = 'nurse'

ALL_ROLES = {ROLE_PATIENT, ROLE_ADMIN, ROLE_HEAD, ROLE_NURSE}
STAFF_ROLES = {ROLE_ADMIN, ROLE_HEAD, ROLE_NURSE}
EDITOR_ROLES = {ROLE_ADMIN, ROLE_NURSE}
MONITOR_ROLES = {ROLE_ADMIN, ROLE_HEAD, ROLE_NURSE}
